apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps-data
    port: 20
    targetPort: 20
  - name: ftps-control
    port: 21
    targetPort: 21
  - name: min
    port: 21009
    targetPort: 21009
  - name: mid
    port: 21010
    targetPort: 21010
  - name: mix
    port: 21011
    targetPort: 21011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - liveness.sh
          initialDelaySeconds: 100
          periodSeconds: 10
        ports:
        - containerPort: 20
          name: ftps-data
        - containerPort: 21
          name: ftps-control
        - containerPort: 21009
          name: min
        - containerPort: 21010
          name: mid
        - containerPort: 21011
          name: max
