apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        # livenessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/healthy
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        ports:
        - name: ftps
          containerPort: 21